/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import services.PythonClient;

/**
 *
 * @author Jonas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWelcome = new javax.swing.JPanel();
        jPanelWELCOME2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelSobre = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelTutorial = new javax.swing.JPanel();
        jLabel1TUTORIAL = new javax.swing.JLabel();
        jPanelHistorico = new javax.swing.JPanel();
        jLabel1HISTORICO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuIniciar = new javax.swing.JMenu();
        jMenuItemWelcome = new javax.swing.JMenuItem();
        jMenuItemRunWithout = new javax.swing.JMenuItem();
        jMenuItemRunWith = new javax.swing.JMenuItem();
        jMenuItemCalibracao = new javax.swing.JMenuItem();
        jMenuItemExtracao = new javax.swing.JMenuItem();
        jMenuItemReconstrucao = new javax.swing.JMenuItem();
        jMenuHistorico = new javax.swing.JMenu();
        jMenuItemCalibrações = new javax.swing.JMenuItem();
        jMenuItemFrames = new javax.swing.JMenuItem();
        jMenuItemVolumes = new javax.swing.JMenuItem();
        jMenuTutorial = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanelWelcome.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanelWelcome.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelWelcome.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bem-vindo ao [Nome do Aplicativo]!");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html> <div style=\"text-align: center;\">Este aplicativo foi desenvolvido para realizar análise volumétrica de objetos por meio de técnicas de visão computacional, permitindo o cálculo de volumes a partir do processamento e análise de imagens. </div>   </html>");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/application.png"))); // NOI18N
        jLabel4.setText("<html><b>Iniciar:</b> Comece aqui. Carregue um novo arquivo de vídeo para realizar a reconstrução 3D e o cálculo volumétrico.</html>");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/database.png"))); // NOI18N
        jLabel5.setText("<html><b>Histórico:</b> Acesse o banco de dados de análises anteriores, visualize resultados salvos e métricas de processamento.</html>");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/application_xp_terminal.png"))); // NOI18N
        jLabel6.setText("<html><b>Tutorial:</b> Dúvidas na captura? Veja o guia passo a passo de como filmar o objeto para obter a melhor precisão.</html>");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/information.png"))); // NOI18N
        jLabel7.setText("<html><b>Sobre:</b> Conheça a tecnologia por trás do projeto e a equipe de desenvolvimento.</html>");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/cross.png"))); // NOI18N
        jLabel8.setText("<html><b>Sair:</b> Encerrar o aplicativo.</html>");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("<html> <div style=\"text-align: center;\">Para navegar, utilize o menu superior. Aqui está o que você pode fazer: </div> </html>");

        javax.swing.GroupLayout jPanelWELCOME2Layout = new javax.swing.GroupLayout(jPanelWELCOME2);
        jPanelWELCOME2.setLayout(jPanelWELCOME2Layout);
        jPanelWELCOME2Layout.setHorizontalGroup(
            jPanelWELCOME2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWELCOME2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWELCOME2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        jPanelWELCOME2Layout.setVerticalGroup(
            jPanelWELCOME2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWELCOME2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jPanelWelcome.add(jPanelWELCOME2, "telaInicial");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sobre o Projeto");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("<html> <div style=\"text-align: center\"> <p>O <b>[Nome do Aplicativo]</b> é um software desenvolvido para reconstrução 3D e estimativa de volume a partir de arquivos de vídeo, utilizando Visão Computacional.</p></div></html>");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html> <div style=\"text-align: center\">\n<b>Java Swing:</b> Interface gráfica do usuário (GUI). <br>         \n<b>Python:</b> Backend e processamento numérico. <br>         \n<b>Flask API:</b> Comunicação entre Interface e Backend. <br>         \n<b>OpenCV:</b> Processamento e análise de imagens. <br>         \n<b>Open3D:</b> Manipulação de nuvens de pontos e malhas. <br>         \n<b>SfM (COLMAP):</b> Reconstrução 3D a partir de múltiplas imagens.\n</div> </html>");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("<html> <div style=\"text-align: center\"> <h2 style='text-align: center;'>Equipe de Desenvolvimento</h2> \nJonas<br>Bruno<br>Tiago<br>Sofia<br>Mateus<br>Zeca<br><br>\n<p><i>Instituto de Ciências Exatas e Aplicadas - ICEA/UFOP</i></p> </div> </html>");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanelSobreLayout = new javax.swing.GroupLayout(jPanelSobre);
        jPanelSobre.setLayout(jPanelSobreLayout);
        jPanelSobreLayout.setHorizontalGroup(
            jPanelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addContainerGap())
            .addGroup(jPanelSobreLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSobreLayout.setVerticalGroup(
            jPanelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobreLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        jPanelWelcome.add(jPanelSobre, "telaSobre");

        jLabel1TUTORIAL.setText("JPANEL TUTORIAL");

        javax.swing.GroupLayout jPanelTutorialLayout = new javax.swing.GroupLayout(jPanelTutorial);
        jPanelTutorial.setLayout(jPanelTutorialLayout);
        jPanelTutorialLayout.setHorizontalGroup(
            jPanelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTutorialLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel1TUTORIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanelTutorialLayout.setVerticalGroup(
            jPanelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTutorialLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1TUTORIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jPanelWelcome.add(jPanelTutorial, "telaTutorial");

        jLabel1HISTORICO.setText("JPANEL HISTORICO (calibrações, frames, volumes)");

        javax.swing.GroupLayout jPanelHistoricoLayout = new javax.swing.GroupLayout(jPanelHistorico);
        jPanelHistorico.setLayout(jPanelHistoricoLayout);
        jPanelHistoricoLayout.setHorizontalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel1HISTORICO, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanelHistoricoLayout.setVerticalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1HISTORICO, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        jPanelWelcome.add(jPanelHistorico, "telaHistorico");

        jLabel1.setText("BEM-Vindo");
        jPanelWelcome.add(jLabel1, "card6");

        jMenuIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/application.png"))); // NOI18N
        jMenuIniciar.setText("Iniciar");

        jMenuItemWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/house.png"))); // NOI18N
        jMenuItemWelcome.setText("Menu inicial");
        jMenuItemWelcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWelcomeActionPerformed(evt);
            }
        });
        jMenuIniciar.add(jMenuItemWelcome);

        jMenuItemRunWithout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/application_go.png"))); // NOI18N
        jMenuItemRunWithout.setText("Execução normal");
        jMenuIniciar.add(jMenuItemRunWithout);

        jMenuItemRunWith.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/application_view_tile.png"))); // NOI18N
        jMenuItemRunWith.setText("Execução com tutorial");
        jMenuIniciar.add(jMenuItemRunWith);

        jMenuItemCalibracao.setText("Calibração da câmera");
        jMenuItemCalibracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCalibracaoActionPerformed(evt);
            }
        });
        jMenuIniciar.add(jMenuItemCalibracao);

        jMenuItemExtracao.setText("Extração de frames");
        jMenuItemExtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExtracaoActionPerformed(evt);
            }
        });
        jMenuIniciar.add(jMenuItemExtracao);

        jMenuItemReconstrucao.setText("Reconstrução da cena");
        jMenuItemReconstrucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReconstrucaoActionPerformed(evt);
            }
        });
        jMenuIniciar.add(jMenuItemReconstrucao);

        jMenuBar.add(jMenuIniciar);

        jMenuHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/database.png"))); // NOI18N
        jMenuHistorico.setText("Histórico");
        jMenuHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHistoricoMouseClicked(evt);
            }
        });

        jMenuItemCalibrações.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/camera.png"))); // NOI18N
        jMenuItemCalibrações.setText("Calibrações");
        jMenuHistorico.add(jMenuItemCalibrações);

        jMenuItemFrames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/film.png"))); // NOI18N
        jMenuItemFrames.setText("Frames");
        jMenuHistorico.add(jMenuItemFrames);

        jMenuItemVolumes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/calculator.png"))); // NOI18N
        jMenuItemVolumes.setText("Volumes");
        jMenuHistorico.add(jMenuItemVolumes);

        jMenuBar.add(jMenuHistorico);

        jMenuTutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/application_xp_terminal.png"))); // NOI18N
        jMenuTutorial.setText("Tutorial");
        jMenuTutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTutorialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuTutorial);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/information.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuSobre);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/cross.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuSair);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuTutorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTutorialMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelWelcome.getLayout();
        cl.show(jPanelWelcome, "telaTutorial");
        
    }//GEN-LAST:event_jMenuTutorialMouseClicked

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
        
        Object[] opcoes = {"Sim", "Cancelar"};
        
        int opcao = JOptionPane.showOptionDialog(
                this, 
                "Deseja sair do sistema?", 
                "Confirmação", 
                JOptionPane.DEFAULT_OPTION, 
                JOptionPane.WARNING_MESSAGE, 
                null,
                opcoes, 
                opcoes[1]
        );
        
        if (opcao == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelWelcome.getLayout();
        cl.show(jPanelWelcome, "telaSobre");
        
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jMenuHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHistoricoMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelWelcome.getLayout();
        cl.show(jPanelWelcome, "telaHistorico");
        
    }//GEN-LAST:event_jMenuHistoricoMouseClicked

    private void jMenuItemCalibracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalibracaoActionPerformed
        // TODO add your handling code here:
        try {
            String resposta = PythonClient.calibrarCamera();
            JOptionPane.showMessageDialog(this, resposta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao executar calibração");
        }
    }//GEN-LAST:event_jMenuItemCalibracaoActionPerformed

    private void jMenuItemExtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExtracaoActionPerformed
        // TODO add your handling code here:
        try {
            String resposta = PythonClient.extrairFrames();
            JOptionPane.showMessageDialog(this, resposta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao executar extração");
        }
    }//GEN-LAST:event_jMenuItemExtracaoActionPerformed

    private void jMenuItemReconstrucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReconstrucaoActionPerformed
        // TODO add your handling code here:
        try {
            String resposta = PythonClient.reconstruir();
            JOptionPane.showMessageDialog(this, resposta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao executar reconstrução");
        }
    }//GEN-LAST:event_jMenuItemReconstrucaoActionPerformed

    private void jMenuItemWelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWelcomeActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelWelcome.getLayout();
        cl.show(jPanelWelcome, "telaInicial");
    }//GEN-LAST:event_jMenuItemWelcomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel1HISTORICO;
    private javax.swing.JLabel jLabel1TUTORIAL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuHistorico;
    private javax.swing.JMenu jMenuIniciar;
    private javax.swing.JMenuItem jMenuItemCalibracao;
    private javax.swing.JMenuItem jMenuItemCalibrações;
    private javax.swing.JMenuItem jMenuItemExtracao;
    private javax.swing.JMenuItem jMenuItemFrames;
    private javax.swing.JMenuItem jMenuItemReconstrucao;
    private javax.swing.JMenuItem jMenuItemRunWith;
    private javax.swing.JMenuItem jMenuItemRunWithout;
    private javax.swing.JMenuItem jMenuItemVolumes;
    private javax.swing.JMenuItem jMenuItemWelcome;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JMenu jMenuTutorial;
    private javax.swing.JPanel jPanelHistorico;
    private javax.swing.JPanel jPanelSobre;
    private javax.swing.JPanel jPanelTutorial;
    private javax.swing.JPanel jPanelWELCOME2;
    private javax.swing.JPanel jPanelWelcome;
    // End of variables declaration//GEN-END:variables
}
