/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import services.PythonClient;

/**
 *
 * @author Jonas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWelcome = new javax.swing.JPanel();
        jLabel3WELCOME = new javax.swing.JLabel();
        jPanelSobre = new javax.swing.JPanel();
        jLabel2SOBRE = new javax.swing.JLabel();
        jPanelTutorial = new javax.swing.JPanel();
        jLabel1TUTORIAL = new javax.swing.JLabel();
        jPanelHistorico = new javax.swing.JPanel();
        jLabel1HISTORICO = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuIniciar = new javax.swing.JMenu();
        jMenuItemWelcome = new javax.swing.JMenuItem();
        jMenuItemRunWithout = new javax.swing.JMenuItem();
        jMenuItemRunWith = new javax.swing.JMenuItem();
        jMenuItemCalibracao = new javax.swing.JMenuItem();
        jMenuItemExtracao = new javax.swing.JMenuItem();
        jMenuItemReconstrucao = new javax.swing.JMenuItem();
        jMenuHistorico = new javax.swing.JMenu();
        jMenuItemCalibrações = new javax.swing.JMenuItem();
        jMenuItemFrames = new javax.swing.JMenuItem();
        jMenuItemVolumes = new javax.swing.JMenuItem();
        jMenuTutorial = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanelWelcome.setMaximumSize(new java.awt.Dimension(1600, 900));
        jPanelWelcome.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelWelcome.setLayout(new java.awt.CardLayout());

        jLabel3WELCOME.setText("JPANEL WELCOME");
        jPanelWelcome.add(jLabel3WELCOME, "card4");

        jLabel2SOBRE.setText("JPANEL SOBRE");

        javax.swing.GroupLayout jPanelSobreLayout = new javax.swing.GroupLayout(jPanelSobre);
        jPanelSobre.setLayout(jPanelSobreLayout);
        jPanelSobreLayout.setHorizontalGroup(
            jPanelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobreLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel2SOBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanelSobreLayout.setVerticalGroup(
            jPanelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSobreLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel2SOBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jPanelWelcome.add(jPanelSobre, "telaSobre");

        jLabel1TUTORIAL.setText("JPANEL TUTORIAL");

        javax.swing.GroupLayout jPanelTutorialLayout = new javax.swing.GroupLayout(jPanelTutorial);
        jPanelTutorial.setLayout(jPanelTutorialLayout);
        jPanelTutorialLayout.setHorizontalGroup(
            jPanelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTutorialLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel1TUTORIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanelTutorialLayout.setVerticalGroup(
            jPanelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTutorialLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1TUTORIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jPanelWelcome.add(jPanelTutorial, "telaTutorial");

        jLabel1HISTORICO.setText("JPANEL HISTORICO (calibrações, frames, volumes)");

        javax.swing.GroupLayout jPanelHistoricoLayout = new javax.swing.GroupLayout(jPanelHistorico);
        jPanelHistorico.setLayout(jPanelHistoricoLayout);
        jPanelHistoricoLayout.setHorizontalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel1HISTORICO, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanelHistoricoLayout.setVerticalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1HISTORICO, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        jPanelWelcome.add(jPanelHistorico, "telaHistorico");

        jMenuIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/application.png"))); // NOI18N
        jMenuIniciar.setText("Iniciar");

        jMenuItemWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/house.png"))); // NOI18N
        jMenuItemWelcome.setText("Menu inicial");
        jMenuIniciar.add(jMenuItemWelcome);

        jMenuItemRunWithout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/application_go.png"))); // NOI18N
        jMenuItemRunWithout.setText("Execução normal");
        jMenuIniciar.add(jMenuItemRunWithout);

        jMenuItemRunWith.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/application_view_tile.png"))); // NOI18N
        jMenuItemRunWith.setText("Execução com tutorial");
        jMenuIniciar.add(jMenuItemRunWith);

        jMenuItemCalibracao.setText("Calibração da câmera");
        jMenuItemCalibracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCalibracaoActionPerformed(evt);
            }
        });
        jMenuIniciar.add(jMenuItemCalibracao);

        jMenuItemExtracao.setText("Extração de frames");
        jMenuItemExtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExtracaoActionPerformed(evt);
            }
        });
        jMenuIniciar.add(jMenuItemExtracao);

        jMenuItemReconstrucao.setText("Reconstrução da cena");
        jMenuItemReconstrucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReconstrucaoActionPerformed(evt);
            }
        });
        jMenuIniciar.add(jMenuItemReconstrucao);

        jMenuBar.add(jMenuIniciar);

        jMenuHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/database.png"))); // NOI18N
        jMenuHistorico.setText("Histórico");
        jMenuHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHistoricoMouseClicked(evt);
            }
        });

        jMenuItemCalibrações.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/camera.png"))); // NOI18N
        jMenuItemCalibrações.setText("Calibrações");
        jMenuHistorico.add(jMenuItemCalibrações);

        jMenuItemFrames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/film.png"))); // NOI18N
        jMenuItemFrames.setText("Frames");
        jMenuHistorico.add(jMenuItemFrames);

        jMenuItemVolumes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/calculator.png"))); // NOI18N
        jMenuItemVolumes.setText("Volumes");
        jMenuHistorico.add(jMenuItemVolumes);

        jMenuBar.add(jMenuHistorico);

        jMenuTutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/application_xp_terminal.png"))); // NOI18N
        jMenuTutorial.setText("Tutorial");
        jMenuTutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTutorialMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuTutorial);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/information.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuSobre);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/cross.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuSair);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuTutorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTutorialMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelWelcome.getLayout();
        cl.show(jPanelWelcome, "telaTutorial");
        
    }//GEN-LAST:event_jMenuTutorialMouseClicked

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
        
        Object[] opcoes = {"Sim", "Cancelar"};
        
        int opcao = JOptionPane.showOptionDialog(
                this, 
                "Deseja sair do sistema?", 
                "Confirmação", 
                JOptionPane.DEFAULT_OPTION, 
                JOptionPane.WARNING_MESSAGE, 
                null,
                opcoes, 
                opcoes[1]
        );
        
        if (opcao == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelWelcome.getLayout();
        cl.show(jPanelWelcome, "telaSobre");
        
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jMenuHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHistoricoMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanelWelcome.getLayout();
        cl.show(jPanelWelcome, "telaHistorico");
        
    }//GEN-LAST:event_jMenuHistoricoMouseClicked

    private void jMenuItemCalibracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalibracaoActionPerformed
        // TODO add your handling code here:
        try {
            String resposta = PythonClient.calibrarCamera();
            JOptionPane.showMessageDialog(this, resposta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao executar calibração");
        }
    }//GEN-LAST:event_jMenuItemCalibracaoActionPerformed

    private void jMenuItemExtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExtracaoActionPerformed
        // TODO add your handling code here:
        try {
            String resposta = PythonClient.extrairFrames();
            JOptionPane.showMessageDialog(this, resposta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao executar extração");
        }
    }//GEN-LAST:event_jMenuItemExtracaoActionPerformed

    private void jMenuItemReconstrucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReconstrucaoActionPerformed
        // TODO add your handling code here:
        try {
            String resposta = PythonClient.reconstruir();
            JOptionPane.showMessageDialog(this, resposta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao executar reconstrução");
        }
    }//GEN-LAST:event_jMenuItemReconstrucaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1HISTORICO;
    private javax.swing.JLabel jLabel1TUTORIAL;
    private javax.swing.JLabel jLabel2SOBRE;
    private javax.swing.JLabel jLabel3WELCOME;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuHistorico;
    private javax.swing.JMenu jMenuIniciar;
    private javax.swing.JMenuItem jMenuItemCalibracao;
    private javax.swing.JMenuItem jMenuItemCalibrações;
    private javax.swing.JMenuItem jMenuItemExtracao;
    private javax.swing.JMenuItem jMenuItemFrames;
    private javax.swing.JMenuItem jMenuItemReconstrucao;
    private javax.swing.JMenuItem jMenuItemRunWith;
    private javax.swing.JMenuItem jMenuItemRunWithout;
    private javax.swing.JMenuItem jMenuItemVolumes;
    private javax.swing.JMenuItem jMenuItemWelcome;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JMenu jMenuTutorial;
    private javax.swing.JPanel jPanelHistorico;
    private javax.swing.JPanel jPanelSobre;
    private javax.swing.JPanel jPanelTutorial;
    private javax.swing.JPanel jPanelWelcome;
    // End of variables declaration//GEN-END:variables
}
